version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - API_PORT=8002
      - API_HOST=0.0.0.0
      - DATABASE_URL=sqlite:///./aims.db
      - SECRET_KEY=development-secret-key
      - LOG_LEVEL=DEBUG
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8002 --reload
    networks:
      - aims-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NEXT_PUBLIC_API_URL=http://localhost:8002/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8002/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - aims-network

networks:
  aims-network:
    driver: bridge

volumes:
  aims_data: