#!/bin/bash

# Development Startup Script for AIMS
# This script starts both frontend and backend services
# Generated by Agent OS to prevent setup amnesia

set -e  # Exit on error

echo "🚀 Starting AIMS Development Environment"
echo "================================================="

# Load environment variables
if [ -f .env ]; then
    echo "📋 Loading backend environment from .env"
    # Read .env file line by line, handling inline comments
    while IFS= read -r line; do
        # Skip empty lines and lines starting with #
        if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
            # Remove inline comments and trim whitespace
            clean_line=$(echo "$line" | cut -d'#' -f1 | sed 's/[[:space:]]*$//')
            if [[ -n "$clean_line" ]]; then
                export "$clean_line"
            fi
        fi
    done < .env
fi

if [ -f frontend/.env.local ]; then
    echo "📋 Loading frontend environment from frontend/.env.local"
    # Read .env.local file line by line
    while IFS= read -r line; do
        if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
            clean_line=$(echo "$line" | cut -d'#' -f1 | sed 's/[[:space:]]*$//')
            if [[ -n "$clean_line" ]]; then
                export "$clean_line"
            fi
        fi
    done < frontend/.env.local
fi

# Get ports from environment or use defaults
BACKEND_PORT=${API_PORT:-8002}
FRONTEND_PORT=${PORT:-3002}

# Backend startup
echo ""
echo "📡 Starting Backend Server on port $BACKEND_PORT..."

if [ -d . ]; then
    source .venv/bin/activate || uv venv && source .venv/bin/activate
    uv pip install -r requirements.txt || uv sync
    uvicorn src.api.main:app --reload --port $BACKEND_PORT --host 0.0.0.0 &
fi

# Frontend startup  
echo ""
echo "🎨 Starting Frontend Server on port $FRONTEND_PORT..."
cd frontend

if [ -d . ]; then
    yarn install  
    yarn dev &
fi

echo ""
echo "✅ Development servers started!"
echo "   Frontend: http://localhost:$FRONTEND_PORT"
echo "   Backend:  http://localhost:$BACKEND_PORT"
echo "   API Docs: http://localhost:$BACKEND_PORT/docs"
echo ""
echo "Press Ctrl+C to stop all services"
wait