"""add_report_email_deliveries_table

Revision ID: f971b81fc8ec
Revises: fe8cf6a04b65
Create Date: 2025-07-29 06:30:34.064909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f971b81fc8ec'
down_revision: Union[str, None] = 'fe8cf6a04b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create report_email_deliveries table
    op.create_table('report_email_deliveries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('email_address', sa.String(length=255), nullable=False),
        sa.Column('delivery_status', sa.String(length=20), nullable=True, server_default='pending'),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for report_email_deliveries
    op.create_index(op.f('ix_report_email_deliveries_id'), 'report_email_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_report_email_deliveries_report_id'), 'report_email_deliveries', ['report_id'], unique=False)
    op.create_index('idx_report_delivery_status', 'report_email_deliveries', ['report_id', 'delivery_status'], unique=False)
    
    # Add missing index for monthly reports optimization (already exists in model but may not be in DB)
    op.create_index('idx_monthly_reports', 'reports', ['user_id', 'report_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop monthly reports index
    op.drop_index('idx_monthly_reports', table_name='reports')
    
    # Drop report_email_deliveries table and indexes
    op.drop_index('idx_report_delivery_status', table_name='report_email_deliveries')
    op.drop_index(op.f('ix_report_email_deliveries_report_id'), table_name='report_email_deliveries')
    op.drop_index(op.f('ix_report_email_deliveries_id'), table_name='report_email_deliveries')
    op.drop_table('report_email_deliveries')
    # ### end Alembic commands ###
