"""Add drawdown tracking fields and DrawdownEvent table

Revision ID: fe8cf6a04b65
Revises: 
Create Date: 2025-07-28 10:07:42.301830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8cf6a04b65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create drawdown_events table
    op.create_table('drawdown_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('peak_value', sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column('trough_value', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('recovery_value', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('max_drawdown_amount', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('max_drawdown_percent', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('duration_days', sa.Integer(), nullable=True),
        sa.Column('recovery_days', sa.Integer(), nullable=True),
        sa.Column('is_recovered', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drawdown_events_user_date', 'drawdown_events', ['user_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_drawdown_events_id'), 'drawdown_events', ['id'], unique=False)
    op.create_index(op.f('ix_drawdown_events_user_id'), 'drawdown_events', ['user_id'], unique=False)
    
    # Add columns to performance_snapshots
    op.add_column('performance_snapshots', sa.Column('portfolio_high_water_mark', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('performance_snapshots', sa.Column('current_drawdown', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('performance_snapshots', sa.Column('current_drawdown_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('performance_snapshots', sa.Column('days_in_drawdown', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from performance_snapshots
    op.drop_column('performance_snapshots', 'days_in_drawdown')
    op.drop_column('performance_snapshots', 'current_drawdown_percent')
    op.drop_column('performance_snapshots', 'current_drawdown')
    op.drop_column('performance_snapshots', 'portfolio_high_water_mark')
    
    # Drop drawdown_events table and indexes
    op.drop_index(op.f('ix_drawdown_events_user_id'), table_name='drawdown_events')
    op.drop_index(op.f('ix_drawdown_events_id'), table_name='drawdown_events')
    op.drop_index('idx_drawdown_events_user_date', table_name='drawdown_events')
    op.drop_table('drawdown_events')
    # ### end Alembic commands ###
